/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, number | string, number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AgentRuns {
  campaign_id: string | null;
  created_at: Int8;
  goal_id: string | null;
  id: string;
  idempotency_key: string | null;
  input_json: string | null;
  kind: string;
  output_json: string | null;
  project_id: string;
  rationale: string | null;
}

export interface AudienceVersions {
  agent_run_id: string | null;
  created_at: Int8;
  created_by: Generated<string>;
  expression_hash: string;
  expression_json: string;
  id: string;
  project_id: string;
  reason: string | null;
  schema_version: number;
  segment_id: string | null;
  segment_version: number | null;
}

export interface CampaignExecutionState {
  campaign_id: string;
  last_processed_at: Int8;
  recipient_cursor: string | null;
}

export interface Campaigns {
  audience_version_id: string | null;
  channel: Generated<string>;
  created_at: Int8;
  created_by: Generated<string>;
  deliver_from: Int8 | null;
  deliver_until: Int8 | null;
  ended_at: Int8 | null;
  goal_id: string | null;
  hypothesis: string | null;
  id: string;
  name: string;
  pages_json: string | null;
  project_id: string;
  started_at: Int8 | null;
  status: Generated<string>;
  targeting_json: string | null;
}

export interface Deliveries {
  bounced_at: Int8 | null;
  campaign_id: string;
  clicked_at: Int8 | null;
  complained_at: Int8 | null;
  converted_at: Int8 | null;
  delivered_at: Int8 | null;
  dismissed_at: Int8 | null;
  end_user_id: string;
  id: string;
  opened_at: Int8 | null;
  provider_message_id: string | null;
  queued_at: Int8;
  send_attempted_at: Int8 | null;
  sent_at: Int8 | null;
  shown_at: Int8 | null;
  state: Generated<string>;
  unsubscribed_at: Int8 | null;
  variant_id: string;
}

export interface EmailSuppressions {
  email: string;
  project_id: string;
  reason: string;
  suppressed_at: Int8;
}

export interface EndUsers {
  external_user_id: string;
  first_seen_at: Int8;
  id: string;
  last_seen_at: Int8;
  project_id: string;
  traits_json: string | null;
}

export interface Events {
  end_user_id: string;
  id: string;
  name: string;
  project_id: string;
  props_json: string | null;
  ts: Int8;
}

export interface Goals {
  approval_mode: Generated<string>;
  created_at: Int8;
  description: string | null;
  guardrails_json: string | null;
  id: string;
  name: string;
  project_id: string;
  status: Generated<string>;
  target_event: string | null;
}

export interface Segments {
  created_at: Int8;
  created_by: Generated<string>;
  current_version: Generated<number>;
  description: string | null;
  id: string;
  idempotency_key: string | null;
  key: string;
  name: string;
  project_id: string;
  status: Generated<string>;
  updated_at: Int8;
}

export interface Variants {
  campaign_id: string;
  content_json: string;
  id: string;
  is_control: Generated<boolean>;
  name: string;
  weight: Generated<number>;
}

export interface ProductDB {
  agent_runs: AgentRuns;
  audience_versions: AudienceVersions;
  campaign_execution_state: CampaignExecutionState;
  campaigns: Campaigns;
  deliveries: Deliveries;
  email_suppressions: EmailSuppressions;
  end_users: EndUsers;
  events: Events;
  goals: Goals;
  segments: Segments;
  variants: Variants;
}
